# Generated by Django 5.1.5 on 2025-01-22 20:48

import resume_form.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeSubmit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('celphone', models.CharField(max_length=15)),
                ('position', models.CharField(max_length=100)),
                ('education', models.CharField(choices=[('fundamental', 'Ensino Fundamental'), ('medio', 'Ensino Médio'), ('superior', 'Ensino Superior'), ('pos', 'Pós-graduação')], max_length=50)),
                ('observations', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='curriculos/', validators=[resume_form.models.validate_file_size])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField()),
            ],
        ),
    ]
