# Generated by Django 5.1.5 on 2025-01-23 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_form', '0002_alter_resumesubmit_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumesubmit',
            old_name='celphone',
            new_name='phone',
        ),
    ]
